apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-website-ingress
  namespace: argocd
  labels:
    app: django-deployment
  annotations:
    # Ingress Core Settings
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-website-service
                port:
                  number: 80